file:
  /usr/local/bin/distro-wrapper:
    exists: true
    owner: distro
    group: root
    filetype: file
  /usr/local/bin/distro:
    exists: true
    owner: distro
    group: root
    filetype: file
package:
  ansible:
    installed: true
  curl:
    installed: true
  git:
    installed: true
  go:
    installed: false
  libc-dev:
    installed: false
  mysql-client:
    installed: true
  nodejs:
    installed: false
  openssh-client-default:
    installed: true
  tini:
    installed: true
user:
  distro:
    exists: true
    uid: 1001
    gid: 0
    home: /home/distro
command:
  distro:
    exit-status: 0
    timeout: 10000
