# Goreleaser configuration
# for building binaries and packages for distributions and releasing on github
dist: bin

before:
  hooks:
    - task compile

builds:
  - binary: distro
    env:
      - CGO_ENABLED=0
    main: ./cli/main.go
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      #- openbsd
      #- netbsd
    goarch:
      - amd64
      #- 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
#    hooks:
#      pre: task compile

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

signs:
  -
    artifacts: checksum
    args: ["-u", "F83D885FC3A9C6875F1C94F1DF6DB3D9E521DB5F", "--pinentry-mode", "loopback", "--yes", "--batch", "--output", "${signature}", "--detach-sign", "${artifact}"]

# Start the snapshot name with a numerical value
# so it does not need to be force installed
snapshot:
  name_template: "{{ .Timestamp }}-{{ .ShortCommit }}-SNAPSHOT"

nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Md Sulaiman
    homepage: https://github.com/khulnasoft-lab/distro
    maintainer: Md Sulaiman <infosulaimanbd@gmail.com>
    description: Open Source alternative to Ansible Tower
    license: MIT

    formats:
      - deb
      - rpm

    # Packages your package depends on.
    dependencies:
      - git

    suggests:
      - ansible

    # install binary in /usr/bin
    bindir: /usr/bin

release:
  # Do not auto publish release
  draft: true
  name_template: "{{.Tag}}"
