version: '2'

volumes:
  data:

services:
  distro_ci:
    image: distroui/distro:ci-compose
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/ci/Dockerfile
    environment:
      DISTRO_DB_DIALECT: bolt
      DISTRO_ADMIN_PASSWORD: password
      DISTRO_ADMIN_NAME: "Developer"
      DISTRO_ADMIN_EMAIL: admin@localhost
      DISTRO_ADMIN: admin
      DISTRO_WEB_ROOT: http://0.0.0.0:3000
      DISTRO_ACCESS_KEY_ENCRYPTION: "IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ="
    ports:
      - "3000:3000"
    volumes:
      - data:/var/lib/distro

  dredd:
    image: distroui/dredd:ci
    command: [ "--config", ".dredd/dredd.yml" ]
    environment:
      DISTRO_ACCESS_KEY_ENCRYPTION: "IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ="
      DISTRO_DB_DIALECT: bolt
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/ci/dredd.Dockerfile
    depends_on:
      - distro_ci
    volumes:
      - data:/data

